# dialogs/rapport_form_etang_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_etangDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "Date_Visite",
            "Nom_Proprio",
            "Num_Tel",
            "Courriel",
            "Adresse",
            "Municipalite",
            "No_Cadastre",
            "CoordGPSX",
            "CoordGPSY",
            "Sous_BV",
            "Caract_Zonage",
            "Caract_OccPrinc",
            "Caract_PressAmont",
            "MH_Amont",
            "MH_Aval",
            "Amenag_Type",
            "Amenag_LienHydro",
            "Amenag_LienOui",
            "Amenag_Baign",
            "Amenag_Rive",
            "Amenag_Expo",
            "Amenag_ProfMax",
            "Amenag_ProfMin",
            "Amenag_ProfMoy",
            "Amenag_Perim",
            "VegAqua_Cyano",
            "VegAqua_CyanoAv",
            "VegAqua_Presence",
            "VegAqua_Emerg",
            "VegAqua_Flott",
            "VegAqua_Submer",
            "VegAqua_EauLibr",
            "EEE_Poiss",
            "EEE_Veg",
            "Turb_Visuel",
            "Turb_JTU",
            "Turb_FortePluie",
            "Sed_MES",
            "Sed_Argile",
            "Sed_Limon",
            "Sed_Sable",
            "Sed_Degre",
            "Sed_Enlisement",
            "Gest_Proprio",
            "Gest_SystEau",
            "Gest_SystType",
            "Gest_Vidang",
            "Gest_VidMeth",
            "Gest_VidFrequ",
            "Gest_Services",
            "Gest_ServicesOui",
            "Autres_Comm",
        ]

        sections = {
            "Général": [
                "Date_Visite",
                "Nom_Proprio",
                "Num_Tel",
                "Courriel",
                "Adresse",
                "Municipalite",
                "No_Cadastre",
                "CoordGPSX",
                "CoordGPSY",
                "Sous_BV",
                "Autres_Comm",
            ],
            "Caractérisation du terrain": [
                "Caract_Zonage",
                "Caract_OccPrinc",
                "Caract_PressAmont",
                "MH_Amont",
                "MH_Aval",
            ],
            "Aménagement de l'étang": [
                "Amenag_Type",
                "Amenag_LienHydro",
                "Amenag_LienOui",
                "Amenag_Baign",
                "Amenag_Rive",
                "Amenag_Expo",
                "Amenag_ProfMax",
                "Amenag_ProfMin",
                "Amenag_ProfMoy",
                "Amenag_Perim",
            ],
            "Bande riveraine": [
            ],
            "Végétation aquatiques": [
                "VegAqua_Cyano",
                "VegAqua_CyanoAv",
                "VegAqua_Presence",
                "VegAqua_Emerg",
                "VegAqua_Flott",
                "VegAqua_Submer",
                "VegAqua_EauLibr",
            ],
            "Espèces envahissantes": [
                "EEE_Poiss",
                "EEE_Veg",
            ],
            "Érosion": [
            ],
            "Sédiments": [
                "Turb_Visuel",
                "Turb_JTU",
                "Turb_FortePluie",
                "Sed_MES",
                "Sed_Degre",
                "Sed_Enlisement",
            ],
            "Pourcentage des composantes du sol (prendre une poignée)": [
                "Sed_Argile",
                "Sed_Limon",
                "Sed_Sable",
            ],
            "Propriétés chimiques": [
            ],
            "Au fond et à 1 mètre si possible": [
            ],
            "À 1 mètre (si possible et si le fond est à plus de 1m)": [
            ],
            "Gestion de l'eau de l'étang": [
                "Gest_Proprio",
                "Gest_SystEau",
                "Gest_SystType",
                "Gest_Vidang",
                "Gest_VidMeth",
                "Gest_VidFrequ",
                "Gest_Services",
                "Gest_ServicesOui",
            ],
        }

        super().__init__("Form_Etang", champs, sections)
