# dialogs/rapport_form_caractcourseau_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_caractcourseauDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "Comment",
            "Nm_CrEau",
            "Caract_Station",
            "Typ_Milieu",
            "Connectivite",
            "Typ_Ecoul",
            "Cond_Hydro",
            "Typ_Tronc",
            "Orig_Ecoul",
            "Dir_Ecoul",
            "Prop_VegAqua",
            "Struct_Anth",
            "Prof_Moy",
            "Larg_Eau",
            "Larg_LitMin",
            "Pres_Debris",
            "Eros_Lit",
            "Comment_Perturb",
            "Subst_RocMer",
            "Subst_GrosBloc",
            "Subst_Bloc",
            "Subst_Galet",
            "Subst_Caillou",
            "Subst_Grav",
            "Subst_Sab",
            "Subst_Lim",
            "Subst_Arg",
            "Subst_LitFor",
            "Subst_DebOrg",
            "Subst_Autre",
            "Rec_PltEmerg",
            "Rec_PltFlot",
            "Rec_PltSubm",
            "Rec_Tot",
            "Org_Lit",
            "Obstacle",
            "Methode_Biophys",
            "Stab_Riv_Trav",
            "Autre_Rive",
            "G_Eros_Pct",
            "G_Perturb_Pct",
            "G_Perturb_Typ",
            "D_Eros_Pct",
            "D_Perturb_Pct",
            "D_Perturb_Typ",
            "Recouv_Veget_Nat",
            "Sol_Perturb",
            "Veget_Coup",
            "HabPois_Choix",
            "Hab_Poiss",
            "PotentPois_Choix",
            "Potent_Poiss",
            "Hab_Choix",
            "Hab_Autre",
            "Esp_Choix",
            "EspFaun_Obs",
        ]

        sections = {
            "Eau": [
                "Comment",
            ],
            "Description": [
                "Nm_CrEau",
                "Caract_Station",
                "Typ_Milieu",
                "Connectivite",
            ],
            "Littoral": [
                "Typ_Ecoul",
                "Cond_Hydro",
                "Typ_Tronc",
                "Orig_Ecoul",
                "Dir_Ecoul",
                "Prop_VegAqua",
                "Struct_Anth",
                "Prof_Moy",
                "Larg_Eau",
                "Larg_LitMin",
                "Pres_Debris",
                "Eros_Lit",
                "Comment_Perturb",
            ],
            "Substrat": [
                "Subst_RocMer",
                "Subst_GrosBloc",
                "Subst_Bloc",
                "Subst_Galet",
                "Subst_Caillou",
                "Subst_Grav",
                "Subst_Sab",
                "Subst_Lim",
                "Subst_Arg",
                "Subst_LitFor",
                "Subst_DebOrg",
                "Subst_Autre",
            ],
            "Recouvrement moyen (%)": [
                "Rec_PltEmerg",
                "Rec_PltFlot",
                "Rec_PltSubm",
                "Rec_Tot",
            ],
            "Organisation du lit": [
                "Org_Lit",
                "Obstacle",
            ],
            "Méthode Biophysique": [
                "Methode_Biophys",
            ],
            "Érosion": [
            ],
            "Rive": [
                "Stab_Riv_Trav",
                "Autre_Rive",
            ],
            "Gauche": [
                "G_Eros_Pct",
                "G_Perturb_Pct",
                "G_Perturb_Typ",
            ],
            "Droite": [
                "D_Eros_Pct",
                "D_Perturb_Pct",
                "D_Perturb_Typ",
            ],
            "Végétation": [
                "Recouv_Veget_Nat",
                "Sol_Perturb",
                "Veget_Coup",
            ],
            "Habitats particuliers": [
                "HabPois_Choix",
                "Hab_Poiss",
                "PotentPois_Choix",
                "Potent_Poiss",
                "Hab_Choix",
                "Hab_Autre",
                "Esp_Choix",
                "EspFaun_Obs",
            ],
        }

        super().__init__("Form_CaractCoursEau", champs, sections)
