# dialogs/rapport_form_iqbr_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_iqbrDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "IQBR_Choix",
            "IQBR_Rive",
            "IQBR_Milieu",
            "IQBR_TypCult",
            "DLargRepl",
            "DSolNu",
            "DHerb",
            "DArbu",
            "DArbr",
            "DAutre",
            "GLargRepl",
            "GSolNu",
            "GHerb",
            "GArbu",
            "GArbr",
            "GAutre",
            "DLHE",
            "DAngPente",
            "DCoupFor",
            "DPrairiFi",
            "DPatu",
            "DCult",
            "DSocRoc",
            "DInfra",
            "DGazon",
            "GLHE",
            "GAngPente",
            "GCoupFor",
            "GPrairFi",
            "GPatu",
            "GCult",
            "GSocRoc",
            "GInfra",
            "GGazon",
            "DIQBR",
            "DLargBR",
            "GIQBR",
            "GLargBR",
            "IQBR_Comment",
        ]

        sections = {
            "Général": [
                "IQBR_Choix",
                "IQBR_Comment",
            ],
            "Simplifiée": [
                "IQBR_Rive",
                "IQBR_Milieu",
            ],
            "Sans titre": [
                "IQBR_TypCult",
            ],
            "Droite (valeurs en %)": [
                "DLargRepl",
                "DSolNu",
                "DHerb",
                "DArbu",
                "DArbr",
                "DAutre",
            ],
            "Gauche (valeurs en %)": [
                "GLargRepl",
                "GSolNu",
                "GHerb",
                "GArbu",
                "GArbr",
                "GAutre",
            ],
            "Droite": [
                "DLargRepl",
                "DLHE",
                "DAngPente",
                "DArbr",
                "DArbu",
                "DHerb",
                "DCoupFor",
                "DPrairiFi",
                "DPatu",
                "DCult",
                "DSolNu",
                "DSocRoc",
                "DInfra",
                "DGazon",
            ],
            "Gauche": [
                "GLargRepl",
                "GLHE",
                "GAngPente",
                "GArbr",
                "GArbu",
                "GHerb",
                "GCoupFor",
                "GPrairFi",
                "GPatu",
                "GCult",
                "GSolNu",
                "GSocRoc",
                "GInfra",
                "GGazon",
            ],
            "Bilan (IQBR)": [
                "DIQBR",
                "DLargBR",
                "GIQBR",
                "GLargBR",
            ],
        }

        super().__init__("Form_IQBR", champs, sections)
