# dialogs/rapport_form_iqm_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_iqmDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "iqm16",
            "copyright",
            "obs",
            "date",
            "nom_riv",
            "troncon",
            "confinemen",
            "longueur",
            "notesgener",
            "iqm",
            "indic_complet",
            "val_max",
            "iqm_partiel",
            "c1_desc",
            "c1_pt",
            "c2_desc",
            "c2_pt",
            "c3_desc",
            "c3_pt",
            "c_comment",
            "a1_desc",
            "a1_pt",
            "a2_desc",
            "a2_pt",
            "a3_desc",
            "a3_pt",
            "a4_desc",
            "a4_pt",
            "a5_desc",
            "a5_pt",
            "a6_desc",
            "a6_pt",
            "a9_desc_1",
            "a9_pt_1",
            "a10_desc",
            "a10_pt",
            "a11_desc",
            "a11_pt",
            "a12_desc",
            "a12_pt",
            "a7_desc",
            "a7_pt",
            "a8_desc",
            "a8_pt",
            "a_comment",
            "f1_desc",
            "f1_pt",
            "f9_desc",
            "f9_pt",
            "f10_desc",
            "f10_pt",
            "f11_desc",
            "f11_pt",
            "f12_desc",
            "f12_pt",
            "f13_desc",
            "f13_pt",
            "f3_desc",
            "f3_pt",
            "f6_desc",
            "f6_pt",
            "f2_desc",
            "f2_pt",
            "f4_desc",
            "f4_pt",
            "f5_desc",
            "f5_pt",
            "f7_desc",
            "f7_pt",
            "f8_desc",
            "f8_pt",
            "f_comment",
        ]

        sections = {
            "Général": [
                "c1_desc",
                "c1_pt",
                "c2_desc",
                "c2_pt",
                "c3_desc",
                "c3_pt",
                "c_comment",
                "a1_desc",
                "a1_pt",
                "a2_desc",
                "a2_pt",
                "a3_desc",
                "a3_pt",
                "a4_desc",
                "a4_pt",
                "a5_desc",
                "a5_pt",
                "a6_desc",
                "a6_pt",
                "a9_desc_1",
                "a9_pt_1",
                "a10_desc",
                "a10_pt",
                "a11_desc",
                "a11_pt",
                "a12_desc",
                "a12_pt",
                "a7_desc",
                "a7_pt",
                "a8_desc",
                "a8_pt",
            ],
            "Métadonnées": [
            ],
            "Version": [
                "iqm16",
                "copyright",
            ],
            "Édition et mise à jour": [
                "obs",
                "date",
            ],
            "Tronçon": [
            ],
            "Propriétés du tronçon": [
                "nom_riv",
                "troncon",
                "confinemen",
                "longueur",
                "notesgener",
            ],
            "Diagnostic": [
                "iqm",
            ],
            "IQM proxi": [
                "indic_complet",
                "val_max",
                "iqm_partiel",
            ],
            "Ajustements": [
            ],
            "Patrons observés au niveau du chenal (trajectoire historique)": [
                "a_comment",
            ],
            "Anthropisation": [
            ],
            "Tronçons confinés ou non confinés": [
                "f1_desc",
                "f1_pt",
                "f9_desc",
                "f9_pt",
                "f10_desc",
                "f10_pt",
                "f11_desc",
                "f11_pt",
                "f12_desc",
                "f12_pt",
                "f13_desc",
                "f13_pt",
            ],
            "Tronçons non confinés seulement": [
                "f2_desc",
                "f2_pt",
                "f4_desc",
                "f4_pt",
                "f5_desc",
                "f5_pt",
                "f7_desc",
                "f7_pt",
                "f8_desc",
                "f8_pt",
            ],
            "Fonctionnement Géomorphologique": [
                "f_comment",
            ],
            "Tronçons confinés seulement": [
                "f3_desc",
                "f3_pt",
                "f6_desc",
                "f6_pt",
            ],
        }

        super().__init__("Form_IQM", champs, sections)
