# dialogs/rapport_form_ponceau_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_ponceauDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "ponc_choix",
            "No_Traverse",
            "Evaluateur",
            "Date",
            "Meteo_Actu",
            "Meteo_Preced",
            "Municipalite",
            "region",
            "domaine",
            "Route",
            "Classe_Route",
            "Precision",
            "Comment",
            "Nom_CrEau",
            "Coord_Y",
            "Coord_X",
            "Type_Infra",
            "Dist_Ponceaux",
            "Materiaux",
            "Diametre",
            "Portee",
            "Etat_Infra",
            "Type_Ecoul",
            "LNHE",
            "Pct_Obstr",
            "Type_Obstr",
            "Cause_Obstr",
            "Prob_Castor",
            "Souce_EroSed",
            "Hauteur_Libre",
            "Largeur_Route",
            "dist_chem",
            "Longueur_Ponceau",
            "Hauteur_Remblai",
            "Pente_Conf",
            "Stab_Conf",
            "Geot_Conf",
            "Long_TuyAmont",
            "Long_TuyAval",
            "Obst_Poiss",
            "Observ_Poiss",
            "Pres_Fray",
            "Connect_CE",
            "Type_Substrat",
            "Prob_Tuy",
            "Acc_MachLourde",
            "Recomm",
            "Recomm1",
            "photo1",
            "photo2",
            "photo_5",
            "photo3",
            "Facies_Ecoul",
            "Pres_HP",
            "iqhp",
            "Comment_Hab",
            "hab_prop",
            "pois_obs",
            "pech_elec",
            "EEE",
            "Comment_Perturb",
            "Esp_Statut",
            "Comment_EspStatut",
            "Nb_Ponc",
            "Cond_Debit",
            "Cond_Trav",
            "Align_Trav",
            "Larg_Rembl",
            "Conf_Rembl",
            "Bass_Aff_Aval",
            "Resser",
            "Comment_Trav",
            "Forme_Sortie",
            "Armnt_Sortie",
            "Gradient_Sortie",
            "dist_strcthaut",
            "dist_strctfond",
            "Larg_Struct",
            "Haut_Struct",
            "SubtEau_Struct",
            "ProfEau_Struct",
            "haut_but",
            "EntSort_Diff",
            "Forme_Entree",
            "Type_Entree",
            "Gradient_Entree",
            "Larg_Struct_Entree",
            "Haut_Struct_Entree",
            "SubstEau_Struct_Entree",
            "ProfEau_Struct_Entree",
            "prf_rad",
            "enf_haut",
            "enf_bas",
            "prof_am2",
            "prof_av2",
            "pont_port",
            "thal_am",
            "haut_ponam",
            "bas_ponam",
            "route_am",
            "thal_av",
            "haut_ponav",
            "bas_ponav",
            "route_av",
            "Pente_Struct",
            "Pentes_Sembl",
            "pente_diff",
            "Struct_Inter",
            "Substr_Sembl",
            "Substr_Inter",
            "CouvSubstr_Inter",
            "Pres_Ero",
            "Comment_Ero",
            "Barr_Phys",
            "ProfEau_Sembl",
            "VitDebit_Sembl",
            "PassSec_Struct",
            "Haut_PassSec",
            "Comment_Struct",
            "Cond_Struct",
            "Photo_1",
            "Photo_2",
            "Photo_3",
            "Photo_4",
        ]

        sections = {
            "Général": [
                "Evaluateur",
                "Meteo_Actu",
                "Meteo_Preced",
                "region",
                "domaine",
                "Route",
                "Classe_Route",
                "Precision",
                "Comment",
                "dist_chem",
                "hab_prop",
                "pois_obs",
                "pech_elec",
                "EEE",
                "Cond_Debit",
                "Larg_Rembl",
                "Conf_Rembl",
                "dist_strcthaut",
                "dist_strctfond",
                "haut_but",
                "prf_rad",
                "enf_haut",
                "enf_bas",
                "prof_am2",
                "prof_av2",
                "pont_port",
                "thal_am",
                "haut_ponam",
                "bas_ponam",
                "route_am",
                "thal_av",
                "haut_ponav",
                "bas_ponav",
                "route_av",
                "Pentes_Sembl",
            ],
            "Version": [
                "ponc_choix",
            ],
            "Identification et localisation": [
                "No_Traverse",
                "Date",
                "Municipalite",
                "Nom_CrEau",
                "Coord_Y",
                "Coord_X",
            ],
            "Sans titre": [
                "PassSec_Struct",
                "Haut_PassSec",
            ],
            "Caractérisation": [
                "Type_Infra",
                "Materiaux",
                "Etat_Infra",
                "Type_Ecoul",
                "Pct_Obstr",
                "Type_Obstr",
                "Cause_Obstr",
                "Souce_EroSed",
                "Hauteur_Libre",
                "Largeur_Route",
                "Longueur_Ponceau",
                "Hauteur_Remblai",
                "Pente_Conf",
                "Stab_Conf",
                "Geot_Conf",
                "Obst_Poiss",
                "Observ_Poiss",
                "Pres_Fray",
                "Connect_CE",
                "Type_Substrat",
                "Prob_Tuy",
                "Acc_MachLourde",
                "Recomm",
                "Recomm1",
            ],
            "Précision (Ponceau parallèle)": [
                "Dist_Ponceaux",
            ],
            "Précision (Type d'infrastructure ou Matériaux)": [
                "Diametre",
                "Portee",
            ],
            "Précision (Type d'écoulement)": [
                "LNHE",
            ],
            "Précision (Castor)": [
                "Prob_Castor",
            ],
            "Longueur du tuyau à la base du remblai": [
                "Long_TuyAmont",
                "Long_TuyAval",
            ],
            "Photo(s)": [
                "photo1",
                "photo2",
                "photo_5",
                "photo3",
            ],
            "Habitat cours d'eau": [
                "Facies_Ecoul",
                "Pres_HP",
                "iqhp",
                "Comment_Hab",
            ],
            "Perturbation et menace": [
                "Observ_Poiss",
                "Comment_Perturb",
            ],
            "Pertubration": [
            ],
            "EEE": [
            ],
            "Espèce faunique ou floristique à statut précaire": [
                "Esp_Statut",
                "Comment_EspStatut",
            ],
            "Espèce à statut": [
            ],
            "Information sur la traverse": [
                "Type_Infra",
                "Nb_Ponc",
                "Cond_Trav",
                "Align_Trav",
                "Bass_Aff_Aval",
                "Resser",
                "Comment_Trav",
            ],
            "Caractéristiques de la structure": [
                "Materiaux",
                "EntSort_Diff",
            ],
            "Sortie": [
                "Forme_Sortie",
                "Armnt_Sortie",
                "Gradient_Sortie",
                "Larg_Struct",
                "Haut_Struct",
                "Longueur_Ponceau",
                "SubtEau_Struct",
                "ProfEau_Struct",
            ],
            "Entrée": [
                "Forme_Entree",
                "Type_Entree",
                "Gradient_Entree",
                "Larg_Struct_Entree",
                "Haut_Struct_Entree",
                "SubstEau_Struct_Entree",
                "ProfEau_Struct_Entree",
            ],
            "Conditions additionelles": [
                "Pente_Struct",
                "pente_diff",
                "Struct_Inter",
                "Substr_Sembl",
                "Substr_Inter",
                "CouvSubstr_Inter",
                "Pres_Ero",
                "Barr_Phys",
                "ProfEau_Sembl",
                "VitDebit_Sembl",
                "Comment_Struct",
                "Cond_Struct",
            ],
            "Érosion": [
                "Comment_Ero",
            ],
            "Barrière": [
            ],
            "Photos": [
                "Photo_1",
                "Photo_2",
                "Photo_3",
                "Photo_4",
                "photo_5",
                "photo3",
            ],
        }

        super().__init__("Form_Ponceau", champs, sections)
