# dialogs/rapport_form_herbier_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_herbierDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "version_choix",
            "Type",
            "Recouvr_HerbTot",
            "Plantes_imm",
            "Plantes_emerg",
            "Plantes_flott",
            "Recouvr_EEETot",
            "EEE_imm",
            "EEE_emerg",
            "EEE_flott",
            "Noms_EEE",
            "Autres_EEE",
            "lac",
            "meteo",
            "surface_eau",
            "profondeur_visibilite",
            "acces_eau",
            "subst_dom1",
            "subst_dom2",
            "periphyton",
            "description_milieu",
            "aire_m2",
            "latitude",
            "longitude",
            "pourc_recouv_herbier",
            "nuisance_deplacement",
            "myriophylle _epi_recouvrement",
            "myriophylle _epi_sociabilite",
            "sp1_herbier",
            "sp1_pourc_recouv",
            "sp1_sociabilite",
            "sp2_herbier",
            "sp2_pourc_recouv",
            "sp2_sociabilite",
            "sp3_herbier",
            "sp3_pourc_recouv",
            "sp3_sociabilite",
            "sp4_herbier",
            "sp4_pourc_recouv",
            "sp4_sociabilite",
            "sp5_herbier",
            "sp5_pourc_recouv",
            "sp5_sociabilite",
            "sp6_herbier",
            "sp6_pourc_recouv",
            "sp6_sociabilite",
            "sp7_herbier",
            "sp7_pourc_recouv",
            "sp7_sociabilite",
            "sp8_herbier",
            "sp8_pourc_recouv",
            "sp8_sociabilite",
            "sp9_herbier",
            "sp9_pourc_recouv",
            "sp9_sociabilite",
            "sp10_herbier",
            "sp10_pourc_recouv",
            "sp10_sociabilite",
            "sp11_herbier",
            "sp11_pourc_recouv",
            "sp11_sociabilite",
            "sp12_herbier",
            "sp12_pourc_recouv",
            "sp12_sociabilite",
            "sp13_herbier",
            "sp13_pourc_recouv",
            "sp13_sociabilite",
            "sp14_herbier",
            "sp14_pourc_recouv",
            "sp14_sociabilite",
            "sp15_herbier",
            "sp15_pourc_recouv",
            "sp15_sociabilite",
            "sp16_herbier",
            "sp16_pourc_recouv",
            "sp16_sociabilite",
            "sp17_herbier",
            "sp17_pourc_recouv",
            "sp17_sociabilite",
            "sp18_herbier",
            "sp18_pourc_recouv",
            "sp18_sociabilite",
            "sp19_herbier",
            "sp19_pourc_recouv",
            "sp19_sociabilite",
            "sp20_herbier",
            "sp20_pourc_recouv",
            "sp20_sociabilite",
            "commentaire_1",
            "commentaire_2",
        ]

        sections = {
            "Général": [
                "version_choix",
            ],
            "Version simplifiée": [
                "Type",
                "Recouvr_HerbTot",
                "Plantes_imm",
                "Plantes_emerg",
                "Plantes_flott",
                "Recouvr_EEETot",
                "EEE_imm",
                "EEE_emerg",
                "EEE_flott",
                "Noms_EEE",
            ],
            "Si autres": [
                "Autres_EEE",
            ],
            "Version longue": [
            ],
            "Info milieu": [
                "lac",
                "meteo",
                "surface_eau",
                "profondeur_visibilite",
                "acces_eau",
                "subst_dom1",
                "subst_dom2",
                "periphyton",
                "description_milieu",
                "aire_m2",
                "latitude",
                "longitude",
            ],
            "Info herbier": [
                "pourc_recouv_herbier",
                "nuisance_deplacement",
                "myriophylle _epi_recouvrement",
                "myriophylle _epi_sociabilite",
                "sp1_herbier",
                "sp1_pourc_recouv",
                "sp1_sociabilite",
                "sp2_herbier",
                "sp2_pourc_recouv",
                "sp2_sociabilite",
                "sp3_herbier",
                "sp3_pourc_recouv",
                "sp3_sociabilite",
                "sp4_herbier",
                "sp4_pourc_recouv",
                "sp4_sociabilite",
                "sp5_herbier",
                "sp5_pourc_recouv",
                "sp5_sociabilite",
                "sp6_herbier",
                "sp6_pourc_recouv",
                "sp6_sociabilite",
                "sp7_herbier",
                "sp7_pourc_recouv",
                "sp7_sociabilite",
                "sp8_herbier",
                "sp8_pourc_recouv",
                "sp8_sociabilite",
                "sp9_herbier",
                "sp9_pourc_recouv",
                "sp9_sociabilite",
                "sp10_herbier",
                "sp10_pourc_recouv",
                "sp10_sociabilite",
                "sp11_herbier",
                "sp11_pourc_recouv",
                "sp11_sociabilite",
                "sp12_herbier",
                "sp12_pourc_recouv",
                "sp12_sociabilite",
                "sp13_herbier",
                "sp13_pourc_recouv",
                "sp13_sociabilite",
                "sp14_herbier",
                "sp14_pourc_recouv",
                "sp14_sociabilite",
                "sp15_herbier",
                "sp15_pourc_recouv",
                "sp15_sociabilite",
                "sp16_herbier",
                "sp16_pourc_recouv",
                "sp16_sociabilite",
                "sp17_herbier",
                "sp17_pourc_recouv",
                "sp17_sociabilite",
                "sp18_herbier",
                "sp18_pourc_recouv",
                "sp18_sociabilite",
                "sp19_herbier",
                "sp19_pourc_recouv",
                "sp19_sociabilite",
                "sp20_herbier",
                "sp20_pourc_recouv",
                "sp20_sociabilite",
                "commentaire_1",
                "commentaire_2",
            ],
        }

        super().__init__("Form_Herbier", champs, sections)
