# dialogs/rapport_form_plantat_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_plantatDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "Type",
            "Biod_Dechire",
            "Biod_Ondule",
            "Biod_Place",
            "Biod_1an",
            "Biod_Vege",
            "Tuteur",
            "Ancr_4presents",
            "Ancr_Biod",
            "Arbre_Ess",
            "Arbre_Variete",
            "Arbre_Comm",
            "Arbre_Vivant",
            "Arbre_Endomm",
            "Arbre_EndommType",
            "Spirale_Presente",
            "Tuteur_Fixe",
            "Clim_Present",
            "Clim_Dechire",
            "Climatic_DechireOu",
            "Clim_Fixe",
            "Clim_Replie",
            "Clim_Nuire",
            "Vegetation",
            "validation",
            "verification",
            "entreprise_agricole",
            "proprietaires",
            "no_projet",
            "haie_validee",
            "nom_obv",
            "date_vali",
            "nom_vali",
            "titre_vali",
            "plan_amenagement",
            "mise_plants",
            "humi_sol",
            "paillis_broches",
            "trav_sol",
            "feuillus_mort",
            "coni_mort",
            "arbu_mort",
            "peuplier_mort",
            "indi_comm",
            "planif_plant",
            "qual_eau",
            "reduc_ero",
            "pollinisation",
            "protect_culture",
            "biodiversite",
            "riv_comm",
            "date_doc",
            "estimation_complet",
            "estimation_juste",
            "estimation_signe",
            "estimation_obs",
            "enquete_complet",
            "enquete_juste",
            "enquete_signe",
            "enquete_obs",
            "plan_complet",
            "plan_juste",
            "plan_signe",
            "plan_obs",
            "grille_complet",
            "grille_juste",
            "grille_signe",
            "grille_obs",
            "registre_complet",
            "registre_juste",
            "registre_signe",
            "registre_obs",
            "recomm1",
            "recomm2",
            "recomm3",
            "recomm4",
            "recomm5",
            "suivi_sylvicole",
            "strate_arboree",
            "strate_arbu",
            "strate_herbacee",
            "talus",
            "cours_deau",
            "rotat_culture1",
            "rotat_culture2",
            "rotat_culture3",
            "regie_sol",
            "culture_comm",
            "date_carbone",
            "travaux_carbone",
            "feuillus_vivant",
            "feuillus_dhp",
            "feuillus_hauteur",
            "coni_vivant",
            "coni_dhp",
            "coni_hauteur",
            "peupl_vivant",
            "peupl_dhp",
            "peupl_hauteur",
            "arbu_vivant",
            "arbu_flfr",
        ]

        sections = {
            "Général": [
                "plan_amenagement",
                "mise_plants",
                "humi_sol",
                "paillis_broches",
                "trav_sol",
            ],
            "Formulaire de plantation": [
                "Type",
            ],
            "Biodisque": [
                "Biod_Dechire",
                "Biod_Ondule",
                "Biod_Place",
                "Biod_1an",
                "Biod_Vege",
            ],
            "Ancrage": [
                "Tuteur",
                "Ancr_4presents",
                "Ancr_Biod",
            ],
            "Arbre": [
                "Arbre_Ess",
                "Arbre_Variete",
                "Arbre_Comm",
                "Arbre_Vivant",
                "Arbre_Endomm",
            ],
            "Type de dommage ou cause de mort": [
                "Arbre_EndommType",
            ],
            "Spirale": [
                "Spirale_Presente",
            ],
            "Tuteur": [
                "Tuteur_Fixe",
            ],
            "Gaine": [
                "Clim_Present",
                "Clim_Dechire",
                "Clim_Fixe",
                "Clim_Replie",
                "Clim_Nuire",
            ],
            "Niveau de la déchirure": [
                "Climatic_DechireOu",
            ],
            "Végétation": [
                "Vegetation",
            ],
            "Implantation de bande riveraine": [
                "validation",
                "verification",
            ],
            "Validation": [
                "entreprise_agricole",
                "proprietaires",
                "no_projet",
                "haie_validee",
                "nom_obv",
            ],
            "Terrain": [
                "date_vali",
                "nom_vali",
            ],
            "Aménagement": [
                "suivi_sylvicole",
            ],
            "Qualité de l'aménagement adéquate": [
                "strate_arboree",
                "strate_arbu",
                "strate_herbacee",
                "talus",
                "cours_deau",
                "indi_comm",
            ],
            "Mortalité (Nb/%)": [
                "feuillus_mort",
                "coni_mort",
                "arbu_mort",
                "peuplier_mort",
            ],
            "Écosystème riverain": [
                "planif_plant",
            ],
            "Quels services écosystémiques seront renforcés?": [
                "qual_eau",
                "reduc_ero",
                "pollinisation",
                "protect_culture",
                "biodiversite",
                "riv_comm",
            ],
            "Documentation": [
                "date_doc",
            ],
            "Estimation préliminaire Carbone": [
                "estimation_complet",
                "estimation_juste",
                "estimation_signe",
                "estimation_obs",
            ],
            "Enquête Qualité Carbone": [
                "enquete_complet",
                "enquete_juste",
                "enquete_signe",
                "enquete_obs",
            ],
            "Plan d'aménagement": [
                "plan_complet",
                "plan_juste",
                "plan_signe",
                "plan_obs",
            ],
            "Grille d'évaluation du projet": [
                "grille_complet",
                "grille_juste",
                "grille_signe",
                "grille_obs",
            ],
            "Registre CR": [
                "registre_complet",
                "registre_juste",
                "registre_signe",
                "registre_obs",
            ],
            "Recommandations": [
                "recomm1",
                "recomm2",
                "recomm3",
                "recomm4",
                "recomm5",
            ],
            "Vérification": [
                "entreprise_agricole",
                "proprietaires",
                "no_projet",
                "haie_validee",
                "nom_obv",
                "titre_vali",
            ],
            "Quels services écosystémiques sont renforcés depuis la dernière validation/vérification?": [
                "qual_eau",
                "reduc_ero",
                "pollinisation",
                "protect_culture",
                "biodiversite",
                "riv_comm",
            ],
            "Culture adjacente": [
                "regie_sol",
                "culture_comm",
            ],
            "Rotation de cultures lors des trois dernières années": [
                "rotat_culture1",
                "rotat_culture2",
                "rotat_culture3",
            ],
            "Évaluation carbone": [
                "date_carbone",
                "travaux_carbone",
            ],
            "Feuillus": [
                "feuillus_vivant",
                "feuillus_dhp",
                "feuillus_hauteur",
            ],
            "Conifès": [
                "coni_vivant",
                "coni_dhp",
                "coni_hauteur",
            ],
            "Peupliers": [
                "peupl_vivant",
                "peupl_dhp",
                "peupl_hauteur",
            ],
            "Arbustes": [
                "arbu_vivant",
                "arbu_flfr",
            ],
        }

        super().__init__("Form_Plantat", champs, sections)
