# dialogs/rapport_form_riv_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_rivDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "riverain",
            "recensement",
            "quand_adress",
            "util_baignade",
            "util_peche",
            "util_ski",
            "util_sansmoteur",
            "util_moteur",
            "utli_autre",
            "embarcation",
            "emb_canot",
            "emb_chaloupe",
            "emb_pedalo",
            "emb_pagaie",
            "emb_ponton",
            "emb_kayak",
            "emb_moteur",
            "emb_autre",
            "util_sem",
            "util_soir",
            "util_wkd",
            "util_moment",
            "qualite_eau",
            "qe_pollagri",
            "qe_batmot",
            "qe_rejet",
            "qe_fosse",
            "qe_champ",
            "qe_autre",
            "berge",
            "cohab_usagers",
            "erosion_berges",
            "secu_usagers",
            "vitesse_embarc",
            "qualit_eau",
            "probl_autre",
            "cohabitation",
            "vit_bateau",
            "vague",
            "vague_autre",
            "securite",
            "resolution",
            "resol_autre",
            "recens_date",
            "recens_coordx",
            "recens_coordy",
            "recens_heure",
            "recens_embarc",
            "recens_dir",
            "recens_vitmoteur",
            "recens_haut",
        ]

        sections = {
            "Général": [
                "riverain",
                "recensement",
                "vague_autre",
            ],
            "Pour les riverain.e.s de la rivière": [
                "quand_adress",
                "embarcation",
                "qualite_eau",
                "berge",
                "cohabitation",
                "vit_bateau",
                "vague",
                "securite",
                "resolution",
            ],
            "Comment utilisez-vous la rivière?": [
                "util_baignade",
                "util_peche",
                "util_ski",
                "util_sansmoteur",
                "util_moteur",
                "utli_autre",
            ],
            "Quels types d’embarcations possédez-vous?": [
                "emb_canot",
                "emb_chaloupe",
                "emb_pedalo",
                "emb_pagaie",
                "emb_ponton",
                "emb_kayak",
                "emb_moteur",
                "emb_autre",
            ],
            "Quand les utilisez-vous?": [
                "util_sem",
                "util_soir",
                "util_wkd",
                "util_moment",
            ],
            "Quelle est la cause ou les causes de cette mauvaise qualité d'eau?": [
                "qe_pollagri",
                "qe_batmot",
                "qe_rejet",
                "qe_fosse",
                "qe_champ",
                "qe_autre",
            ],
            "Quels sont, selon vous, les problèmes de la rivière?": [
                "cohab_usagers",
                "erosion_berges",
                "secu_usagers",
                "vitesse_embarc",
                "qualit_eau",
                "probl_autre",
            ],
            "Sans titre": [
                "resol_autre",
            ],
            "Recensement des embarcations à moteur": [
                "recens_date",
                "recens_heure",
                "recens_embarc",
                "recens_dir",
                "recens_haut",
            ],
            "Lieu": [
                "recens_coordx",
                "recens_coordy",
            ],
            "Pour les embarcations à moteur": [
                "recens_vitmoteur",
            ],
        }

        super().__init__("Form_Riv", champs, sections)
