# dialogs/rapport_form_chant_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_chantDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "Secteur",
            "Adresse",
            "Typ_Constr",
            "PreNom_Proprio1",
            "Num_Tel1",
            "PreNom_Proprio2",
            "Num_Tel2",
            "Courriel",
            "Entrepr_Constr",
            "Proprio_Entr",
            "NumTel_Entr",
            "Courriel_Entr",
            "Contact_Terr",
            "Nature_Trav",
            "Date_Debut",
            "Date_Fin",
            "Date_Vis",
            "Prox_CE",
            "Typ_Sol",
            "Pente_Terr",
            "Obs_Pluie",
            "Meteo_Vis",
            "Tablier_Granu",
            "TabGra_PointAcc",
            "Ptgpa_Largeur3point6",
            "Ptgpa_Longueur15",
            "Ptgpa_DepotSedRue",
            "Ptgpa_RecouvrPierres",
            "photo1",
            "Amonc_Deblais",
            "Prob_AmoncDeb",
            "Pead_Moins4m",
            "Pead_Moins30m",
            "Pead_Racine",
            "photo2",
            "ProtEntr_Amonc",
            "Prob_ProtEntrAmonc",
            "Ppead_Baches",
            "Ppead_Paille",
            "Ppead_Clotures",
            "Ppead_NonAdequat",
            "photo3",
            "Confi_Sediment",
            "Prob_ConfSed",
            "Pcs_AbsentesTalus",
            "Pcs_DeterioreesTalus",
            "Pcs_AbsentesZones",
            "Pcs_DeterioreesZones",
            "Pcs_AbsentesBR",
            "Pcs_DeterioreesBR",
            "Pcs_AbsentesPentes",
            "Pcs_DeterioreesPentes",
            "photo4",
            "Entendue",
            "photo5",
            "Revegetal",
            "photo6",
            "Autres_Notes",
            "photo7",
            "Notes_Ville",
            "Date_Envoi",
            "Contact",
            "Media",
        ]

        sections = {
            "Général": [
                "PreNom_Proprio1",
                "Num_Tel1",
                "PreNom_Proprio2",
                "Num_Tel2",
                "Courriel",
                "Entrepr_Constr",
                "Proprio_Entr",
                "NumTel_Entr",
                "Courriel_Entr",
                "Contact_Terr",
            ],
            "Administration": [
                "Secteur",
                "Adresse",
                "Typ_Constr",
            ],
            "Sans titre": [
                "Nature_Trav",
                "Date_Debut",
                "Date_Fin",
                "Date_Vis",
            ],
            "Caractéristiques du terrain": [
                "Prox_CE",
                "Typ_Sol",
                "Pente_Terr",
                "Obs_Pluie",
                "Meteo_Vis",
            ],
            "Ouvrage de contrôle d'érosion et sedimentation": [
                "Tablier_Granu",
                "TabGra_PointAcc",
                "photo1",
                "Amonc_Deblais",
                "Prob_AmoncDeb",
                "photo2",
                "ProtEntr_Amonc",
                "Prob_ProtEntrAmonc",
                "photo3",
                "Confi_Sediment",
                "Prob_ConfSed",
                "photo4",
                "Entendue",
                "photo5",
                "Revegetal",
                "photo6",
                "Autres_Notes",
                "photo7",
                "Notes_Ville",
                "Date_Envoi",
                "Contact",
                "Media",
            ],
            "Problèmatiques Tablier granulaire aux points d'accès": [
                "Ptgpa_Largeur3point6",
                "Ptgpa_Longueur15",
                "Ptgpa_DepotSedRue",
                "Ptgpa_RecouvrPierres",
            ],
            "Problèmatiques Emplacement amoncellement déblais": [
                "Pead_Moins4m",
                "Pead_Moins30m",
                "Pead_Racine",
            ],
            "Problèmatiques Protection et entretien d'amoncellement de déblais": [
                "Ppead_Baches",
                "Ppead_Paille",
                "Ppead_Clotures",
                "Ppead_NonAdequat",
            ],
            "Problèmatique Confinement des sédiments": [
                "Pcs_AbsentesTalus",
                "Pcs_DeterioreesTalus",
                "Pcs_AbsentesZones",
                "Pcs_DeterioreesZones",
                "Pcs_AbsentesBR",
                "Pcs_DeterioreesBR",
                "Pcs_AbsentesPentes",
                "Pcs_DeterioreesPentes",
            ],
        }

        super().__init__("Form_Chant", champs, sections)
