# dialogs/rapport_form_survolbenthos_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_survolbenthosDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "nom-respon",
            "resp-fonct",
            "nom-stat",
            "type-stat",
            "obj-stat",
            "hypo-quali",
            "act-peren",
            "util-donne",
            "nbr-eleves",
            "ratio-sexe",
            "no_echant",
            "nb_cont",
            "cours-eau",
            "observat",
            "date",
            "heure",
            "larg-eau",
            "larg-berge",
            "profondeur",
            "lat-nord",
            "long-ouest",
            "ecoul_1",
            "ecoul_2",
            "ecoul_3",
            "vitesse_1",
            "vitesse_2",
            "vitesse_3",
            "vitesse_4",
            "vitesse_5",
            "vitesse_un",
            "vitesse_me",
            "transpar",
            "couvert",
            "compo_1",
            "compo_2",
            "compo_3",
            "algue",
            "mousse",
            "etat_txt",
            "etat_autre",
            "macrophyte",
            "compo_rg_1",
            "compo_rg_2",
            "compo_rg_3",
            "compo_rg_4",
            "compo_rg_5",
            "compo_rg_6",
            "compo_rg_7",
            "compo_rg_8",
            "compo_rg_9",
            "compo_rd_1",
            "compo_rd_2",
            "compo_rd_3",
            "compo_rd_4",
            "compo_rd_5",
            "compo_rd_6",
            "compo_rd_7",
            "compo_rd_8",
            "compo_rd_9",
            "long_rd",
            "long_rg",
            "soutien_rg",
            "soutien_rd",
            "photo-1",
            "desc1",
            "photo-2",
            "desc2",
            "photo-3",
            "desc3",
            "auteur1",
            "remarque",
            "schema",
            "schema2",
            "schema-des",
            "temp_1",
            "temp_2",
            "temp_3",
            "oxy-A_1",
            "oxy-A_2",
            "oxy-A_3",
            "oxy-B_1",
            "oxy-B_2",
            "oxy-B_3",
            "ph_1",
            "ph_2",
            "ph_3",
            "durete_1",
            "durete_2",
            "durete_3",
            "colif_to_1",
            "colif_to_2",
            "colif_to_3",
            "colif_fe_1",
            "colif_fe_2",
            "colif_fe_3",
            "phospha_1",
            "phospha_2",
            "phospha_3",
            "nitrates_1",
            "nitrates_2",
            "nitrates_3",
            "nitrites_1",
            "nitrites_2",
            "nitrites_3",
            "conduct_1",
            "conduct_2",
            "conduct_3",
            "azote_1",
            "azote_2",
            "azote_3",
            "matiere_1",
            "matiere_2",
            "matiere_3",
            "physi-com",
            "p_substrat",
            "c_substrat",
            "p_ensabl",
            "c_ensabl",
            "p_velocite",
            "c_velocite",
            "p_sedim",
            "c_sedim",
            "p_marnage",
            "c_marnage",
            "p_modif",
            "c_modif",
            "p_seuils",
            "c_seuils",
            "p_stab_rd",
            "c_stab_rd",
            "p_stab_rg",
            "c_stab_rg",
            "p_prot_rd",
            "c_prot_rd",
            "p_prot_rg",
            "c_prot_rg",
            "p_larg_rd",
            "c_larg_rd",
            "p_larg_rg",
            "c_larg_rg",
            "bilan",
        ]

        sections = {
            "Station": [
                "nom-respon",
                "resp-fonct",
                "nom-stat",
                "type-stat",
                "obj-stat",
                "hypo-quali",
                "act-peren",
                "util-donne",
                "nbr-eleves",
                "ratio-sexe",
                "no_echant",
                "nb_cont",
            ],
            "Description de la station": [
                "cours-eau",
                "nom-stat",
                "observat",
                "date",
                "heure",
                "larg-eau",
                "larg-berge",
                "profondeur",
                "transpar",
                "couvert",
            ],
            "Coordonnées GPS": [
                "lat-nord",
                "long-ouest",
            ],
            "Type d'écoulement (%)": [
                "ecoul_1",
                "ecoul_2",
                "ecoul_3",
            ],
            "Vitesse du courant": [
                "vitesse_1",
                "vitesse_2",
                "vitesse_3",
                "vitesse_4",
                "vitesse_5",
                "vitesse_un",
                "vitesse_me",
            ],
            "Type et état du substrat": [
            ],
            "Composition (%)": [
                "compo_1",
                "compo_2",
                "compo_3",
            ],
            "État du substrat": [
                "algue",
                "mousse",
                "etat_txt",
                "etat_autre",
            ],
            "Macrophytes": [
                "macrophyte",
            ],
            "Description des berges": [
            ],
            "Composition rive gauche (%)": [
                "compo_rg_1",
                "compo_rg_2",
                "compo_rg_3",
                "compo_rg_4",
                "compo_rg_5",
                "compo_rg_6",
                "compo_rg_7",
                "compo_rg_8",
                "compo_rg_9",
            ],
            "Composition rive droite (%)": [
                "compo_rd_1",
                "compo_rd_2",
                "compo_rd_3",
                "compo_rd_4",
                "compo_rd_5",
                "compo_rd_6",
                "compo_rd_7",
                "compo_rd_8",
                "compo_rd_9",
            ],
            "Infrastructure de soutien": [
                "long_rd",
                "long_rg",
                "soutien_rg",
                "soutien_rd",
            ],
            "Photographies": [
                "photo-1",
                "desc1",
                "photo-2",
                "desc2",
                "photo-3",
                "desc3",
                "auteur1",
            ],
            "Remarques": [
                "remarque",
            ],
            "Schéma": [
                "schema",
                "schema2",
                "schema-des",
            ],
            "Physicochimie": [
            ],
            "Température (°C)": [
                "temp_1",
                "temp_2",
                "temp_3",
            ],
            "Oxygène dissous (mg/l)": [
                "oxy-A_1",
                "oxy-A_2",
                "oxy-A_3",
            ],
            "Oxygène dissous (% de saturation)": [
                "oxy-B_1",
                "oxy-B_2",
                "oxy-B_3",
            ],
            "pH": [
                "ph_1",
                "ph_2",
                "ph_3",
            ],
            "Dureté (mg/l CaCO3)": [
                "durete_1",
                "durete_2",
                "durete_3",
            ],
            "Coliformes fécaux (UFC/100ml)": [
                "colif_to_1",
                "colif_to_2",
                "colif_to_3",
            ],
            "Coliformes fécaux - E.coli (UFC/100ml)": [
                "colif_fe_1",
                "colif_fe_2",
                "colif_fe_3",
            ],
            "Phosphate (mg/l)": [
                "phospha_1",
                "phospha_2",
                "phospha_3",
            ],
            "Nitrates (mg/l)": [
                "nitrates_1",
                "nitrates_2",
                "nitrates_3",
            ],
            "Nitrites (mg/l)": [
                "nitrites_1",
                "nitrites_2",
                "nitrites_3",
            ],
            "Conductivité (us/cm)": [
                "conduct_1",
                "conduct_2",
                "conduct_3",
            ],
            "Azote ammoniacal (ppm)": [
                "azote_1",
                "azote_2",
                "azote_3",
            ],
            "Matière en suspension (mg/l)": [
                "matiere_1",
                "matiere_2",
                "matiere_3",
            ],
            "Commentaires": [
                "physi-com",
            ],
            "Indice de qualité de l'habitat": [
            ],
            "1 - Substat benthique - disponibilité des abris": [
                "p_substrat",
                "c_substrat",
            ],
            "2 - Ensablement - envasement": [
                "p_ensabl",
                "c_ensabl",
            ],
            "3 - Régime vélocité – profondeur": [
                "p_velocite",
                "c_velocite",
            ],
            "4 - Sédimentation": [
                "p_sedim",
                "c_sedim",
            ],
            "5 - Degré de marnage": [
                "p_marnage",
                "c_marnage",
            ],
            "6 - Modification du cours d'eau": [
                "p_modif",
                "c_modif",
            ],
            "7 - Fréquence des seuils": [
                "p_seuils",
                "c_seuils",
            ],
            "8 - Stabilité des berges rive droite": [
                "p_stab_rd",
                "c_stab_rd",
            ],
            "8 - Stabilité des berges rive gauche": [
                "p_stab_rg",
                "c_stab_rg",
            ],
            "9 - Protection végétale des berges rive droite": [
                "p_prot_rd",
                "c_prot_rd",
            ],
            "9 - Protection végétale des berges rive gauche": [
                "p_prot_rg",
                "c_prot_rg",
            ],
            "10 - Largeur de la bande végétale rive droite": [
                "p_larg_rd",
                "c_larg_rd",
            ],
            "10 - Largeur de la bande végétale rive gauche": [
                "p_larg_rg",
                "c_larg_rg",
            ],
            "Bilan": [
                "bilan",
            ],
        }

        super().__init__("Form_SurvolBenthos", champs, sections)
