# dialogs/rapport_form_ornitho_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_ornithoDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "site_name",
            "geoprivacy",
            "latitude",
            "longitude",
            "precision",
            "access",
            "date",
            "heure_deb",
            "heure_fin",
            "duration",
            "protocol",
            "observers",
            "reported",
            "distance",
            "area",
            "comm_site",
            "photo_site",
            "name",
            "genus",
            "species",
            "statut",
            "nat_obs",
            "nb_male",
            "nb_femelle",
            "nb_adulte",
            "nb_couple",
            "nb_nid",
            "nb_nid_in",
            "nb_oeuf",
            "nb_jeune",
            "nb_immat",
            "nb_indet",
            "number",
            "code_compo",
            "habitat",
            "menaces",
            "act_cons",
            "suivi",
            "comm_obs",
            "photo_obs",
        ]

        sections = {
            "Localisation et effort": [
                "site_name",
                "geoprivacy",
                "latitude",
                "longitude",
                "precision",
                "access",
                "date",
                "heure_deb",
                "heure_fin",
                "duration",
                "protocol",
                "observers",
                "reported",
                "distance",
                "area",
                "comm_site",
                "photo_site",
            ],
            "Observation": [
                "name",
                "genus",
                "species",
                "statut",
                "nat_obs",
                "nb_male",
                "nb_femelle",
                "nb_adulte",
                "nb_couple",
                "nb_nid",
                "nb_nid_in",
                "nb_oeuf",
                "nb_jeune",
                "nb_immat",
                "nb_indet",
                "number",
                "code_compo",
                "habitat",
                "menaces",
                "act_cons",
                "suivi",
                "comm_obs",
                "photo_obs",
            ],
        }

        super().__init__("Form_Ornitho", champs, sections)
